// ============================================================
// Intents Schema
// User/governance goals parsed into structured form.
// Represents a user's statement of intent before strategy generation.
// ============================================================

import {
  pgTable,
  text,
  real,
  integer,
  jsonb,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { organizations } from "./organizations";
import type { UserIntent } from "@defi-composer/shared";

export const intentStatusEnum = pgEnum("intent_status", [
  "received",
  "planning",
  "ready",            // candidates generated, awaiting user selection
  "selected",         // user picked a strategy
  "executed",
  "cancelled",
  "failed",
]);

export const intents = pgTable("intents", {
  id: text("id").primaryKey(),                    // e.g. "intent_abc123"
  orgId: text("org_id").notNull().references(() => organizations.id),

  // Raw and parsed
  rawText: text("raw_text").notNull(),            // original user input
  parsed: jsonb("parsed").$type<UserIntent>(),    // structured intent

  // Generation state
  status: intentStatusEnum("status").notNull().default("received"),
  candidateCount: integer("candidate_count").default(0),
  selectedStrategyId: text("selected_strategy_id"),
  positionId: text("position_id"),                // set after execution

  // Metadata
  submittedBy: text("submitted_by").notNull(),    // wallet address
  jobId: text("job_id"),                          // BullMQ job ID for polling

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const intentsRelations = relations(intents, ({ one }) => ({
  organization: one(organizations, {
    fields: [intents.orgId],
    references: [organizations.id],
  }),
}));

// ─── Candidate Strategies ─────────────────────────────────
// Generated by planner, associated with an intent
import type { CandidateStrategy } from "@defi-composer/shared";

export const candidateStrategies = pgTable("candidate_strategies", {
  id: text("id").primaryKey(),
  intentId: text("intent_id").notNull().references(() => intents.id, { onDelete: "cascade" }),
  orgId: text("org_id").notNull(),

  // Full candidate snapshot
  candidate: jsonb("candidate").notNull().$type<CandidateStrategy>(),

  // Denormalized for queries
  rank: integer("rank").notNull(),
  estimatedApyBps: integer("estimated_apy_bps").notNull(),
  riskLevel: text("risk_level").notNull(),        // "low" | "medium" | "high" | "extreme"
  recommended: integer("recommended").notNull().default(0),

  // Model metadata
  modelUsed: text("model_used").notNull().default("deterministic"),
  generationMs: integer("generation_ms"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const candidateStrategiesRelations = relations(candidateStrategies, ({ one }) => ({
  intent: one(intents, {
    fields: [candidateStrategies.intentId],
    references: [intents.id],
  }),
}));
